apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletonapi-deployment
spec:
  selector:
    matchLabels:
      app: skeletonapi
  template:
    metadata:
      labels:
        app: skeletonapi
    spec:
      containers:
      - name: skeletonapi
        image: alountk/skeletonapi:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service
          - name: MongoDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: skeletonapi-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: skeletonapi-service
spec:
  type: LoadBalancer
  selector:
    app: skeletonapi
  ports:
  - port: 80
    targetPort: 80
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: server-cluster-ip-service
# spec:
#   type: NodePort
#   selector:
#     apps: skeletonapi
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 31515

